version: "3.8"

services:
  web:
    build:
      context: .
    container_name: web
    ports:
      - "8000:8000"
    command: ["sh", "./start.sh"]
    env_file:
      - .env
    depends_on:
      - postgres_db
    networks:
      - backend

  postgres_db:
    image: postgres:latest  # Consider pinning to a specific version for consistency
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${SQL_NAME}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
