# Generated by Django 4.2.5 on 2023-10-01 01:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0003_book_available_book_location_book_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_interested',
            field=models.ManyToManyField(related_name='is_interested', to=settings.AUTH_USER_MODEL),
        ),
    ]
