# Generated by Django 4.2.5 on 2023-10-01 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_is_interested'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['genre_name']},
        ),
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
        migrations.AlterModelTable(
            name='images',
            table='image',
        ),
    ]
