# Generated by Django 4.2.5 on 2023-10-01 02:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0007_alter_book_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_interested',
            field=models.ManyToManyField(blank=True, related_name='is_interested', to=settings.AUTH_USER_MODEL),
        ),
    ]
