# Generated by Django 4.2.5 on 2023-10-01 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_is_interested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_image', to='books.book'),
        ),
    ]
